apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels: 
    apps: topo
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: topo
  labels:
    name: topo
    app: topo
  namespace: security
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: topo
        app: topo
    spec:
      # Needed to attach to Host network
      hostNetwork: true
      containers:
        - name: topo
          #image: eu.gcr.io/cluster-1-235110/topo:v0.3
          image: gcr.io/k8sec-215018/topo:v0.3
          securityContext:
            privileged: true
            #readOnlyRootFilesystem: true
            capabilities:
              add: ["CAP_NET_ADMIN"]
          env:
            - name: IFACE 
              value: "any"
            - name: PCAP_FILTER 
              value: "ip"
            - name: SOCAT_HOST 
              value: "nids-01"
            - name: SOCAT_PORT 
              value: "58888"
            # Enable SNAPLENGHT if you are injecting the traffic to an interface
            - name: SNAPLENGHT
              value: "0"
