apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels: 
    apps: topo
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: topo
  labels:
    name: topo
    app: topo
  namespace: security
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: topo
        app: topo
    spec:

      securityContext:
        fsGroup: 2000
      # Needed to attach to Host network
      hostNetwork: true
      containers:
        - name: topo
          image: gcr.io/k8sec-215018/topo
          securityContext:
            privileged: true
            readOnlyRootFilesystem: true
            capabilities:
              add: ["CAP_NET_ADMIN"]
          env:
            - name: IFACE 
              value: "any"
            - name: PCAP_FILTER 
              value: "port 80"
            - name: SOCAT_HOST 
              value: "10.156.0.4"
            - name: SOCAT_PORT 
              value: "8080"
          volumeMounts:
            - mountPath: /sys
              name: sys-fs
      volumes:
        - name: sys-fs
          hostPath:
            path: /sys
